apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://adyanth.github.io/cloudflare-operator/
    chart: cloudflare-operator
    targetRevision: "*"
    helm:
      values: |
        cloudflare:
          apiToken:
            existingSecret: cloudflare-api-token
            key: apiToken
          accountId:
            existingSecret: cloudflare-api-token
            key: accountId
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-operator-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
