apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallabag-tunnel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/roadhouse/infra.git
    targetRevision: HEAD
    path: tunnels/wallabag
    plugin:
      name: sops
  destination:
    server: https://kubernetes.default.svc
    namespace: wallabag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
